# Generated by Django 5.2.1 on 2025-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_rentalapplication_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalapplication",
            name="applied_at",
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
